### ISSUE TITLE
[Epic] Moduł planowania zajęć

### ISSUE THREAD

**Issue by sebkozlo** [TiDzejKej/programowanie-zaawansowane-projekt#1]
### Cel
Umożliwić działowi dydaktyki planowanie harmonogramu zajęć za pomocą interaktywnego kalendarza.

### Zadania
- [ ] API do zarządzania harmonogramami.
- [ ] Widok interaktywnego kalendarza.
- [ ] Funkcja weryfikacji dostępności sal i wykładowców.
- [ ] Obsługa kolizji w harmonogramie.
