### ISSUE TITLE
[Epic] Panel studenta

### ISSUE THREAD

**Issue by sebkozlo** [TiDzejKej/programowanie-zaawansowane-projekt#2]
**Cel**: Umożliwienie studentom przeglądania harmonogramów zajęć oraz wypełniania ankiet oceniających zajęcia.

### Zadania:
- [x] **Podgląd harmonogramu zajęć**
  - [x] Widok harmonogramu przypisany do użytkownika-studenta.
  - [x] Możliwość filtrowania zajęć według daty, grupy lub prowadzącego.
- [x] **Formularz ankiety oceniającej**
  - [x] Tworzenie dynamicznych ankiet po zakończeniu zajęć.
  - [x] Mechanizm oceny w skali oraz możliwość dodania uwag.
- [x] **Integracja z backendem**
  - [x] Stworzenie endpointów do zapisywania odpowiedzi ankiet w bazie danych.
  - [x] Walidacja danych wprowadzanych przez użytkownika.
