### ISSUE TITLE
## [Epic] Panel wykładowcy

### ISSUE THREAD

**Issue by sebkozlo** [TiDzejKej/programowanie-zaawansowane-projekt#3]
*Cel**: Udostępnienie prowadzącym zajęcia narzędzi do podglądu harmonogramu i przeglądania wyników ankiet oceniających.

### Zadania:
- [ ] **Podgląd harmonogramu**
  - [ ] Widok z zajęciami prowadzonymi przez wykładowcę.
  - [ ] Możliwość pobrania harmonogramu w formacie PDF.
- [ ] **Raport z ankiet**
  - [ ] Widok zbiorczego raportu z ocenami i opiniami studentów.
  - [ ] Wizualizacja wyników (np. wykresy).
- [ ] **Notyfikacje**
  - [ ] Powiadomienia o nowych wynikach ankiet.
  - [ ] Automatyczne przypomnienia o nadchodzących zajęciach.
